---
postinstall_pkgs:
    - python-apt
    - apt-transport-https
    - git
    - libssl-dev
    - libbz2-dev
    - libreadline-dev
    - libsqlite3-dev

common_pkgs:
    - htop
    - vim
    - neovim
    - python3-neovim
    - nmap
    - tmux
    - zsh
    - zsh-syntax-highlighting
    - tree
    - dnsutils
    - curl
