---
postinstall_pkgs:
    - python-apt
    - apt-transport-https

common_pkgs:
    - htop
    - vim
    - neovim
    - python3-neovim
    - nmap
    - tmux
    - zsh
    - zsh-syntax-highlighting
    - tree
    - dnsutils
    - curl
