#!/bin/bash
killall conky
sleep 1
#
# 2. asztal
#
(sleep 3 && wmctrl -s 1) &
(sleep 4 && wmctrl -s 1 && conky -c ~/.conky/mon1/hdd/hdd.rc) &
(sleep 4 && wmctrl -s 1 && conky -c ~/Descargas/gitdown/saltedbox/states/debian/conky/conky-osd/mon1/cpu/cpu.rc) &
#(sleep 4 && wmctrl -s 1 && conky -c ~/.conky/mon1/cpu/cpu.rc) &
#(sleep 4 && wmctrl -s 1 && conky -c ~/.conky/mon1/cpu/cpuanim.rc) &
#(sleep 4 && wmctrl -s 1 && conky -c ~/.conky/mon1/net/net.rc) &
#(sleep 4 && wmctrl -s 1 && conky -c ~/.conky/mon1/net/netanim.rc) &
#(sleep 4 && wmctrl -s 1 && conky -c ~/.conky/mon1/net/netanim_wifi.rc) &
#(sleep 4 && wmctrl -s 1 && conky -c ~/.conky/mon1/anim/bdron.rc) &
#(sleep 4 && wmctrl -s 1 && conky -c ~/.conky/mon1/media/mediaas) &
#(sleep 5 && wmctrl -s 1 && conky -c ~/.conky/mon1/media/media_b.rc) &
##
##
## 1. asztal
##
#(sleep 7 && wmctrl -s 0) &
#(sleep 8 && wmctrl -s 0 && conky -c ~/Oblivion/desk1/user/user.rc) &
#(sleep 8 && wmctrl -s 0 && conky -c ~/Oblivion/desk1/process/process.rc) &
#(sleep 8 && wmctrl -s 0 && conky -c ~/Oblivion/desk1/anim/local.rc) &
#(sleep 8 && wmctrl -s 0 && conky -c ~/Oblivion/desk1/weather/weather.rc) &
#(sleep 8 && wmctrl -s 0 && conky -c ~/Oblivion/desk1/cpu_bat/cpu_bat.rc) &
#(sleep 8 && wmctrl -s 0 && conky -c ~/Oblivion/desk1/anim/anim_command_tech.rc) &
#(sleep 8 && wmctrl -s 0 && conky -c ~/Oblivion/desk1/anim/signal.rc) &
#(sleep 9 && wmctrl -s 0 && conky -c ~/Oblivion/desk1/user/useranim.rc) &
#
exit
