version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - run:
          name: Install systems dependencies
          command: sudo apt-get update && sudo apt-get install -y python-pip

      - run:
          name: Install aws-cli and ansible
          command: sudo pip install --upgrade awscli ansible

workflows:
    version: 2
    build-deploy:
        jobs:
            - build
