---
- name: Installing activation packages 
  become: yes
  apt:
      name: "{{ activation_pkgs }}"
      state: latest 

- import_tasks: neovim.yml

- import_tasks: irssi.yml

- import_tasks: zsh.yml
  tags: zsh

- import_tasks: user_env.yml
  tags: basics
