---
- name: "Installing dotfiles... "
  copy:
    src: "dotfiles/{{ item }}"
    dest: "/home/{{ username }}/.{{ item }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644
  loop:
    - bashrc
    - zshrc
    - fonts
    - tmux.conf
      
- name: oh-my-zsh install
  git: "repo=https://github.com/robbyrussell/oh-my-zsh.git dest=/home/{{ username }}/.oh-my-zsh"

  #- name: oh-my-zsh configuration
  #  become: yes
  #  copy:
  #      src: dotfiles/oh-my-zsh
  #      dest: "/home/{{ username }}/.oh-my-zsh"
  #      owner: "{{ username }}"
  #      group: "{{ username }}"
  #      mode: 0755

- name: "Updating fonts cache... "
  shell:
      cmd: "fc-cache -fv >/dev/null"
      chdir: "/home/{{ username }}"
