---
- name: "Copying zsh configuration... "
  copy:
    src: "dotfiles/zshrc"
    dest: "/home/{{ username }}/.zshrc"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644
      
- name: oh-my-zsh install
  become: "{{ username }}"
  git:
    repo: "https://github.com/robbyrussell/oh-my-zsh.git"
    dest: "/home/{{ username }}/.oh-my-zsh"

  #- name: oh-my-zsh configuration
  #  become: yes
  #  copy:
  #      src: dotfiles/oh-my-zsh
  #      dest: "/home/{{ username }}/.oh-my-zsh"
  #      owner: "{{ username }}"
  #      group: "{{ username }}"
  #      mode: 0755
