---
- name: install base packages 
  become: yes
  apt:
      name: "{{ postinstall_pkgs }}"
      state: latest 

- name: sources config
  copy:
      src: sources.list
      dest: /etc/apt/sources.list

- name: update cache
  become: yes
  apt:
      update_cache: yes
      upgrade: dist
      autoclean: yes
      autoremove: yes

- name: install common packages 
  become: yes
  apt:
      name: "{{ common_pkgs }}"
      state: latest 
