---
- name: set hostname
  become: yes
  hostname:
    name: vortex

- name: install base packages 
  become: yes
  apt:
      name: "{{ postinstall_pkgs }}"
      state: latest 

- name: sources config
  copy:
      src: sources.list
      dest: /etc/apt/sources.list

- name: apt pinning
  copy:
      src: preferences
      dest: /etc/apt/preferences

- name: update cache
  become: yes
  apt:
      update_cache: yes
      upgrade: dist
      autoclean: yes
      autoremove: yes
  when: init_pkgs

- name: install common packages 
  become: yes
  apt:
      name: "{{ common_pkgs }}"
      state: latest 
  when: init_pkgs
