---
- hosts: all
  become: yes
  vars:
    - base16_scheme: pop
    - set_awesome: true
    - init_pkgs: true

  roles:
    - role: postinstall
      tags: initial_setup

    - role: activation
      tags: user_setup

    - role: desktop
      tags: desk_setup
