---
- hosts: all
  become: yes
  vars:
    - base16_scheme: pop
    - set_awesome: true
    - init_pkgs: true

  roles:
    - role: postinstall
      tags: initial_setup

    - role: gantsign.oh-my-zsh
      users:
        - username: speedlight

    - role: activation
      tags: user_setup

    - role: desktop
      tags: desktop_setup
